# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docker_host',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='序号')),
                ('ip', models.CharField(max_length=100, verbose_name='ip地址')),
                ('user', models.CharField(default='', max_length=100, verbose_name='用户名')),
                ('logindate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '容器主机',
                'verbose_name_plural': '容器主机',
            },
        ),
    ]
