# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker_host',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='密码'),
        ),
    ]
