# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='镜像id')),
                ('repository', models.CharField(max_length=100, verbose_name='镜像标签')),
            ],
            options={
                'verbose_name': '镜像管理',
                'verbose_name_plural': '镜像管理',
            },
        ),
    ]
