# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.CharField(default='', max_length=50, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(default='', max_length=50, verbose_name='大小'),
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.CharField(default='', max_length=10, verbose_name='镜像标签'),
        ),
        migrations.AlterField(
            model_name='image',
            name='repository',
            field=models.CharField(default='', max_length=100, verbose_name='镜像标签'),
        ),
    ]
