# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_auto_20171222_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='容器id')),
                ('con_port', models.CharField(default='', max_length=100, verbose_name='容器端口')),
                ('name', models.CharField(default='', max_length=50, verbose_name='容器名')),
                ('created', models.CharField(default='', max_length=50, verbose_name='创建时间')),
                ('status', models.CharField(default='', max_length=50, verbose_name='运行状态')),
                ('image', models.CharField(default='', max_length=50, verbose_name='镜像')),
                ('command', models.CharField(default='', max_length=100, verbose_name='容器中命令')),
            ],
            options={
                'verbose_name': '镜像管理',
                'verbose_name_plural': '镜像管理',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='tag',
            field=models.CharField(default='', max_length=10, verbose_name='版本'),
        ),
    ]
