# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_auto_20171225_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='容器名'),
        ),
    ]
